# Emojis utilizados en la aplicación
EMOJI_DEPOSITO = "📥"
EMOJI_RETIRO = "📤"
EMOJI_OK = "✅"
EMOJI_CANCEL = "❌"
EMOJI_WARNING = "⚠️"
EMOJI_INFO = "ℹ️"
EMOJI_CLOCK = "⏰"
EMOJI_MAIL = "📧"

# Textos descriptivos para estados y notificaciones
TEXTO_DEPOSITO_PENDIENTE = f"{EMOJI_DEPOSITO} Depósito pendiente de aprobación"
TEXTO_RETIRO_PENDIENTE = f"{EMOJI_RETIRO} Retiro pendiente de revisión"
TEXTO_DEPOSITO_OK = f"{EMOJI_OK} Depósito registrado exitosamente"
TEXTO_RETIRO_OK = f"{EMOJI_OK} Retiro solicitado correctamente"
TEXTO_ESTADO_PENDIENTE = f"{EMOJI_WARNING} Pendiente de revisión"
TEXTO_ESTADO_COMPLETADO = f"{EMOJI_OK} Completado"
TEXTO_ESTADO_CANCELADO = f"{EMOJI_CANCEL} Cancelado"
TEXTO_TIEMPO = f"{EMOJI_CLOCK} Tiempo estimado: 24 a 48 horas hábiles"
TEXTO_NOTIFICACION = f"{EMOJI_MAIL} Notificación: Recibirás una confirmación cuando el proceso se complete."