EMOJI_DEPOSITO = "📥"
EMOJI_RETIRO = "📤"
EMOJI_OK = "✅"
EMOJI_CANCEL = "❌"
EMOJI_WARNING = "⚠️"
EMOJI_INFO = "ℹ️"
EMOJI_CLOCK = "⏰"
EMOJI_MAIL = "📧"

TEXTO_DEPOSITO_PENDIENTE = f"{EMOJI_DEPOSITO} Depósito Pendiente"
TEXTO_RETIRO_PENDIENTE = f"{EMOJI_RETIRO} Retiro Pendiente"
TEXTO_DEPOSITO_OK = f"{EMOJI_OK} Depósito registrado"
TEXTO_RETIRO_OK = f"{EMOJI_OK} Retiro solicitado"
TEXTO_ESTADO_PENDIENTE = "Pendiente de revisión"
TEXTO_ESTADO_COMPLETADO = "Completado"
TEXTO_ESTADO_CANCELADO = "Cancelado"
TEXTO_TIEMPO = f"{EMOJI_CLOCK} Tiempo estimado: 24-48 horas"
TEXTO_NOTIFICACION = f"{EMOJI_MAIL} Notificación: Recibirás confirmación cuando se complete." 